// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: cp_drama_admin.proto

package drama

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Req struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Req) Reset() {
	*x = Req{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cp_drama_admin_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Req) ProtoMessage() {}

func (x *Req) ProtoReflect() protoreflect.Message {
	mi := &file_cp_drama_admin_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Req.ProtoReflect.Descriptor instead.
func (*Req) Descriptor() ([]byte, []int) {
	return file_cp_drama_admin_proto_rawDescGZIP(), []int{0}
}

type Resp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Resp) Reset() {
	*x = Resp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cp_drama_admin_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Resp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resp) ProtoMessage() {}

func (x *Resp) ProtoReflect() protoreflect.Message {
	mi := &file_cp_drama_admin_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resp.ProtoReflect.Descriptor instead.
func (*Resp) Descriptor() ([]byte, []int) {
	return file_cp_drama_admin_proto_rawDescGZIP(), []int{1}
}

// 作品相关结构体
type DramaInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DramaInfoReq) Reset() {
	*x = DramaInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cp_drama_admin_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DramaInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DramaInfoReq) ProtoMessage() {}

func (x *DramaInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_cp_drama_admin_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DramaInfoReq.ProtoReflect.Descriptor instead.
func (*DramaInfoReq) Descriptor() ([]byte, []int) {
	return file_cp_drama_admin_proto_rawDescGZIP(), []int{2}
}

func (x *DramaInfoReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DramaInfoResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Drama *DramaInfo `protobuf:"bytes,1,opt,name=drama,proto3" json:"drama,omitempty"`
}

func (x *DramaInfoResp) Reset() {
	*x = DramaInfoResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cp_drama_admin_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DramaInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DramaInfoResp) ProtoMessage() {}

func (x *DramaInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_cp_drama_admin_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DramaInfoResp.ProtoReflect.Descriptor instead.
func (*DramaInfoResp) Descriptor() ([]byte, []int) {
	return file_cp_drama_admin_proto_rawDescGZIP(), []int{3}
}

func (x *DramaInfoResp) GetDrama() *DramaInfo {
	if x != nil {
		return x.Drama
	}
	return nil
}

type DramaShortListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids string `protobuf:"bytes,1,opt,name=ids,proto3" json:"ids,omitempty"`
}

func (x *DramaShortListReq) Reset() {
	*x = DramaShortListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cp_drama_admin_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DramaShortListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DramaShortListReq) ProtoMessage() {}

func (x *DramaShortListReq) ProtoReflect() protoreflect.Message {
	mi := &file_cp_drama_admin_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DramaShortListReq.ProtoReflect.Descriptor instead.
func (*DramaShortListReq) Descriptor() ([]byte, []int) {
	return file_cp_drama_admin_proto_rawDescGZIP(), []int{4}
}

func (x *DramaShortListReq) GetIds() string {
	if x != nil {
		return x.Ids
	}
	return ""
}

type DramaShortListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*DramaShort `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *DramaShortListResp) Reset() {
	*x = DramaShortListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cp_drama_admin_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DramaShortListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DramaShortListResp) ProtoMessage() {}

func (x *DramaShortListResp) ProtoReflect() protoreflect.Message {
	mi := &file_cp_drama_admin_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DramaShortListResp.ProtoReflect.Descriptor instead.
func (*DramaShortListResp) Descriptor() ([]byte, []int) {
	return file_cp_drama_admin_proto_rawDescGZIP(), []int{5}
}

func (x *DramaShortListResp) GetList() []*DramaShort {
	if x != nil {
		return x.List
	}
	return nil
}

type DramaInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                  int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Cover               string `protobuf:"bytes,2,opt,name=cover,proto3" json:"cover,omitempty"`
	Name                string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Author              string `protobuf:"bytes,4,opt,name=author,proto3" json:"author,omitempty"`
	Category            int64  `protobuf:"varint,5,opt,name=category,proto3" json:"category,omitempty"`
	CatalogId           int64  `protobuf:"varint,6,opt,name=catalog_id,json=catalogId,proto3" json:"catalog_id,omitempty"`
	Nid                 int64  `protobuf:"varint,7,opt,name=nid,proto3" json:"nid,omitempty"`
	ProducerId          int64  `protobuf:"varint,8,opt,name=producer_id,json=producerId,proto3" json:"producer_id,omitempty"`
	ProducerName        string `protobuf:"bytes,9,opt,name=producer_name,json=producerName,proto3" json:"producer_name,omitempty"`
	Process             int64  `protobuf:"varint,10,opt,name=process,proto3" json:"process,omitempty"`
	ShortIntro          string `protobuf:"bytes,11,opt,name=short_intro,json=shortIntro,proto3" json:"short_intro,omitempty"`
	Intro               string `protobuf:"bytes,12,opt,name=intro,proto3" json:"intro,omitempty"`
	TotalPrice          int64  `protobuf:"varint,13,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	IsPay               int64  `protobuf:"varint,14,opt,name=is_pay,json=isPay,proto3" json:"is_pay,omitempty"`
	PayIndex            int64  `protobuf:"varint,15,opt,name=pay_index,json=payIndex,proto3" json:"pay_index,omitempty"`
	Price               int64  `protobuf:"varint,16,opt,name=price,proto3" json:"price,omitempty"`
	DiscountAll         int64  `protobuf:"varint,17,opt,name=discount_all,json=discountAll,proto3" json:"discount_all,omitempty"`
	DiscountAllEtime    string `protobuf:"bytes,18,opt,name=discount_all_etime,json=discountAllEtime,proto3" json:"discount_all_etime,omitempty"`
	DiscountSingle      int64  `protobuf:"varint,19,opt,name=discount_single,json=discountSingle,proto3" json:"discount_single,omitempty"`
	DiscountSingleEtime string `protobuf:"bytes,20,opt,name=discount_single_etime,json=discountSingleEtime,proto3" json:"discount_single_etime,omitempty"`
	Status              int64  `protobuf:"varint,21,opt,name=status,proto3" json:"status,omitempty"`
	ServerDivided       int64  `protobuf:"varint,22,opt,name=server_divided,json=serverDivided,proto3" json:"server_divided,omitempty"`
	ProducerDivided     int64  `protobuf:"varint,23,opt,name=producer_divided,json=producerDivided,proto3" json:"producer_divided,omitempty"`
}

func (x *DramaInfo) Reset() {
	*x = DramaInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cp_drama_admin_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DramaInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DramaInfo) ProtoMessage() {}

func (x *DramaInfo) ProtoReflect() protoreflect.Message {
	mi := &file_cp_drama_admin_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DramaInfo.ProtoReflect.Descriptor instead.
func (*DramaInfo) Descriptor() ([]byte, []int) {
	return file_cp_drama_admin_proto_rawDescGZIP(), []int{6}
}

func (x *DramaInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DramaInfo) GetCover() string {
	if x != nil {
		return x.Cover
	}
	return ""
}

func (x *DramaInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DramaInfo) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *DramaInfo) GetCategory() int64 {
	if x != nil {
		return x.Category
	}
	return 0
}

func (x *DramaInfo) GetCatalogId() int64 {
	if x != nil {
		return x.CatalogId
	}
	return 0
}

func (x *DramaInfo) GetNid() int64 {
	if x != nil {
		return x.Nid
	}
	return 0
}

func (x *DramaInfo) GetProducerId() int64 {
	if x != nil {
		return x.ProducerId
	}
	return 0
}

func (x *DramaInfo) GetProducerName() string {
	if x != nil {
		return x.ProducerName
	}
	return ""
}

func (x *DramaInfo) GetProcess() int64 {
	if x != nil {
		return x.Process
	}
	return 0
}

func (x *DramaInfo) GetShortIntro() string {
	if x != nil {
		return x.ShortIntro
	}
	return ""
}

func (x *DramaInfo) GetIntro() string {
	if x != nil {
		return x.Intro
	}
	return ""
}

func (x *DramaInfo) GetTotalPrice() int64 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

func (x *DramaInfo) GetIsPay() int64 {
	if x != nil {
		return x.IsPay
	}
	return 0
}

func (x *DramaInfo) GetPayIndex() int64 {
	if x != nil {
		return x.PayIndex
	}
	return 0
}

func (x *DramaInfo) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *DramaInfo) GetDiscountAll() int64 {
	if x != nil {
		return x.DiscountAll
	}
	return 0
}

func (x *DramaInfo) GetDiscountAllEtime() string {
	if x != nil {
		return x.DiscountAllEtime
	}
	return ""
}

func (x *DramaInfo) GetDiscountSingle() int64 {
	if x != nil {
		return x.DiscountSingle
	}
	return 0
}

func (x *DramaInfo) GetDiscountSingleEtime() string {
	if x != nil {
		return x.DiscountSingleEtime
	}
	return ""
}

func (x *DramaInfo) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *DramaInfo) GetServerDivided() int64 {
	if x != nil {
		return x.ServerDivided
	}
	return 0
}

func (x *DramaInfo) GetProducerDivided() int64 {
	if x != nil {
		return x.ProducerDivided
	}
	return 0
}

type DramaShort struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Cover      string `protobuf:"bytes,2,opt,name=cover,proto3" json:"cover,omitempty"`
	Name       string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Author     string `protobuf:"bytes,4,opt,name=author,proto3" json:"author,omitempty"`
	Intro      string `protobuf:"bytes,5,opt,name=intro,proto3" json:"intro,omitempty"`
	ShortIntro string `protobuf:"bytes,6,opt,name=short_intro,json=shortIntro,proto3" json:"short_intro,omitempty"`
}

func (x *DramaShort) Reset() {
	*x = DramaShort{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cp_drama_admin_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DramaShort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DramaShort) ProtoMessage() {}

func (x *DramaShort) ProtoReflect() protoreflect.Message {
	mi := &file_cp_drama_admin_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DramaShort.ProtoReflect.Descriptor instead.
func (*DramaShort) Descriptor() ([]byte, []int) {
	return file_cp_drama_admin_proto_rawDescGZIP(), []int{7}
}

func (x *DramaShort) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DramaShort) GetCover() string {
	if x != nil {
		return x.Cover
	}
	return ""
}

func (x *DramaShort) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DramaShort) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *DramaShort) GetIntro() string {
	if x != nil {
		return x.Intro
	}
	return ""
}

func (x *DramaShort) GetShortIntro() string {
	if x != nil {
		return x.ShortIntro
	}
	return ""
}

// 工作室相关
type Producer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Uid       int64  `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty"`
	Status    int64  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	Mark      string `protobuf:"bytes,5,opt,name=mark,proto3" json:"mark,omitempty"`
	CreatedAt string `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *Producer) Reset() {
	*x = Producer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cp_drama_admin_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Producer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Producer) ProtoMessage() {}

func (x *Producer) ProtoReflect() protoreflect.Message {
	mi := &file_cp_drama_admin_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Producer.ProtoReflect.Descriptor instead.
func (*Producer) Descriptor() ([]byte, []int) {
	return file_cp_drama_admin_proto_rawDescGZIP(), []int{8}
}

func (x *Producer) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Producer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Producer) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *Producer) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Producer) GetMark() string {
	if x != nil {
		return x.Mark
	}
	return ""
}

func (x *Producer) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type ProducerEditReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name   string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Uid    int64  `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty"`
	Status int64  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	Mark   string `protobuf:"bytes,5,opt,name=mark,proto3" json:"mark,omitempty"`
}

func (x *ProducerEditReq) Reset() {
	*x = ProducerEditReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cp_drama_admin_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProducerEditReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProducerEditReq) ProtoMessage() {}

func (x *ProducerEditReq) ProtoReflect() protoreflect.Message {
	mi := &file_cp_drama_admin_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProducerEditReq.ProtoReflect.Descriptor instead.
func (*ProducerEditReq) Descriptor() ([]byte, []int) {
	return file_cp_drama_admin_proto_rawDescGZIP(), []int{9}
}

func (x *ProducerEditReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProducerEditReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProducerEditReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *ProducerEditReq) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ProducerEditReq) GetMark() string {
	if x != nil {
		return x.Mark
	}
	return ""
}

type ProducerEditResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ProducerEditResp) Reset() {
	*x = ProducerEditResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cp_drama_admin_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProducerEditResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProducerEditResp) ProtoMessage() {}

func (x *ProducerEditResp) ProtoReflect() protoreflect.Message {
	mi := &file_cp_drama_admin_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProducerEditResp.ProtoReflect.Descriptor instead.
func (*ProducerEditResp) Descriptor() ([]byte, []int) {
	return file_cp_drama_admin_proto_rawDescGZIP(), []int{10}
}

func (x *ProducerEditResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 工作室相关
type ProducerDictResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*ProducerDict `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *ProducerDictResp) Reset() {
	*x = ProducerDictResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cp_drama_admin_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProducerDictResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProducerDictResp) ProtoMessage() {}

func (x *ProducerDictResp) ProtoReflect() protoreflect.Message {
	mi := &file_cp_drama_admin_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProducerDictResp.ProtoReflect.Descriptor instead.
func (*ProducerDictResp) Descriptor() ([]byte, []int) {
	return file_cp_drama_admin_proto_rawDescGZIP(), []int{11}
}

func (x *ProducerDictResp) GetList() []*ProducerDict {
	if x != nil {
		return x.List
	}
	return nil
}

type ProducerAllReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Order int64 `protobuf:"varint,1,opt,name=order,proto3" json:"order,omitempty"`
}

func (x *ProducerAllReq) Reset() {
	*x = ProducerAllReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cp_drama_admin_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProducerAllReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProducerAllReq) ProtoMessage() {}

func (x *ProducerAllReq) ProtoReflect() protoreflect.Message {
	mi := &file_cp_drama_admin_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProducerAllReq.ProtoReflect.Descriptor instead.
func (*ProducerAllReq) Descriptor() ([]byte, []int) {
	return file_cp_drama_admin_proto_rawDescGZIP(), []int{12}
}

func (x *ProducerAllReq) GetOrder() int64 {
	if x != nil {
		return x.Order
	}
	return 0
}

type ProducerDict struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ProducerDict) Reset() {
	*x = ProducerDict{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cp_drama_admin_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProducerDict) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProducerDict) ProtoMessage() {}

func (x *ProducerDict) ProtoReflect() protoreflect.Message {
	mi := &file_cp_drama_admin_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProducerDict.ProtoReflect.Descriptor instead.
func (*ProducerDict) Descriptor() ([]byte, []int) {
	return file_cp_drama_admin_proto_rawDescGZIP(), []int{13}
}

func (x *ProducerDict) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProducerDict) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ProducerAllResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*Producer `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *ProducerAllResp) Reset() {
	*x = ProducerAllResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cp_drama_admin_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProducerAllResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProducerAllResp) ProtoMessage() {}

func (x *ProducerAllResp) ProtoReflect() protoreflect.Message {
	mi := &file_cp_drama_admin_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProducerAllResp.ProtoReflect.Descriptor instead.
func (*ProducerAllResp) Descriptor() ([]byte, []int) {
	return file_cp_drama_admin_proto_rawDescGZIP(), []int{14}
}

func (x *ProducerAllResp) GetList() []*Producer {
	if x != nil {
		return x.List
	}
	return nil
}

// 推荐相关
type RecPosition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	TempType  int64  `protobuf:"varint,3,opt,name=temp_type,json=tempType,proto3" json:"temp_type,omitempty"`
	Sort      int64  `protobuf:"varint,4,opt,name=sort,proto3" json:"sort,omitempty"`
	NovelIds  string `protobuf:"bytes,5,opt,name=novel_ids,json=novelIds,proto3" json:"novel_ids,omitempty"`
	IsDel     int64  `protobuf:"varint,6,opt,name=is_del,json=isDel,proto3" json:"is_del,omitempty"`
	CreatedAt string `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt string `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (x *RecPosition) Reset() {
	*x = RecPosition{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cp_drama_admin_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecPosition) ProtoMessage() {}

func (x *RecPosition) ProtoReflect() protoreflect.Message {
	mi := &file_cp_drama_admin_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecPosition.ProtoReflect.Descriptor instead.
func (*RecPosition) Descriptor() ([]byte, []int) {
	return file_cp_drama_admin_proto_rawDescGZIP(), []int{15}
}

func (x *RecPosition) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RecPosition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RecPosition) GetTempType() int64 {
	if x != nil {
		return x.TempType
	}
	return 0
}

func (x *RecPosition) GetSort() int64 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *RecPosition) GetNovelIds() string {
	if x != nil {
		return x.NovelIds
	}
	return ""
}

func (x *RecPosition) GetIsDel() int64 {
	if x != nil {
		return x.IsDel
	}
	return 0
}

func (x *RecPosition) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *RecPosition) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type RecPositionReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Limit    int64 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	PageSize int64 `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
}

func (x *RecPositionReq) Reset() {
	*x = RecPositionReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cp_drama_admin_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecPositionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecPositionReq) ProtoMessage() {}

func (x *RecPositionReq) ProtoReflect() protoreflect.Message {
	mi := &file_cp_drama_admin_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecPositionReq.ProtoReflect.Descriptor instead.
func (*RecPositionReq) Descriptor() ([]byte, []int) {
	return file_cp_drama_admin_proto_rawDescGZIP(), []int{16}
}

func (x *RecPositionReq) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *RecPositionReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type RecPositionResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*RecPosition `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *RecPositionResp) Reset() {
	*x = RecPositionResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cp_drama_admin_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecPositionResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecPositionResp) ProtoMessage() {}

func (x *RecPositionResp) ProtoReflect() protoreflect.Message {
	mi := &file_cp_drama_admin_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecPositionResp.ProtoReflect.Descriptor instead.
func (*RecPositionResp) Descriptor() ([]byte, []int) {
	return file_cp_drama_admin_proto_rawDescGZIP(), []int{17}
}

func (x *RecPositionResp) GetList() []*RecPosition {
	if x != nil {
		return x.List
	}
	return nil
}

type RecPositionOpsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *RecPositionOpsReq) Reset() {
	*x = RecPositionOpsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cp_drama_admin_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecPositionOpsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecPositionOpsReq) ProtoMessage() {}

func (x *RecPositionOpsReq) ProtoReflect() protoreflect.Message {
	mi := &file_cp_drama_admin_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecPositionOpsReq.ProtoReflect.Descriptor instead.
func (*RecPositionOpsReq) Descriptor() ([]byte, []int) {
	return file_cp_drama_admin_proto_rawDescGZIP(), []int{18}
}

func (x *RecPositionOpsReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type RecPositionDataReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	NovelIds string `protobuf:"bytes,3,opt,name=novel_ids,json=novelIds,proto3" json:"novel_ids,omitempty"`
	Sort     int64  `protobuf:"varint,4,opt,name=sort,proto3" json:"sort,omitempty"`
	TempType int64  `protobuf:"varint,5,opt,name=temp_type,json=tempType,proto3" json:"temp_type,omitempty"`
}

func (x *RecPositionDataReq) Reset() {
	*x = RecPositionDataReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cp_drama_admin_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecPositionDataReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecPositionDataReq) ProtoMessage() {}

func (x *RecPositionDataReq) ProtoReflect() protoreflect.Message {
	mi := &file_cp_drama_admin_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecPositionDataReq.ProtoReflect.Descriptor instead.
func (*RecPositionDataReq) Descriptor() ([]byte, []int) {
	return file_cp_drama_admin_proto_rawDescGZIP(), []int{19}
}

func (x *RecPositionDataReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RecPositionDataReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RecPositionDataReq) GetNovelIds() string {
	if x != nil {
		return x.NovelIds
	}
	return ""
}

func (x *RecPositionDataReq) GetSort() int64 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *RecPositionDataReq) GetTempType() int64 {
	if x != nil {
		return x.TempType
	}
	return 0
}

type RecPositionAddReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	NovelIds string `protobuf:"bytes,2,opt,name=novel_ids,json=novelIds,proto3" json:"novel_ids,omitempty"`
	Sort     int64  `protobuf:"varint,3,opt,name=sort,proto3" json:"sort,omitempty"`
	TempType int64  `protobuf:"varint,4,opt,name=temp_type,json=tempType,proto3" json:"temp_type,omitempty"`
}

func (x *RecPositionAddReq) Reset() {
	*x = RecPositionAddReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cp_drama_admin_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecPositionAddReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecPositionAddReq) ProtoMessage() {}

func (x *RecPositionAddReq) ProtoReflect() protoreflect.Message {
	mi := &file_cp_drama_admin_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecPositionAddReq.ProtoReflect.Descriptor instead.
func (*RecPositionAddReq) Descriptor() ([]byte, []int) {
	return file_cp_drama_admin_proto_rawDescGZIP(), []int{20}
}

func (x *RecPositionAddReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RecPositionAddReq) GetNovelIds() string {
	if x != nil {
		return x.NovelIds
	}
	return ""
}

func (x *RecPositionAddReq) GetSort() int64 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *RecPositionAddReq) GetTempType() int64 {
	if x != nil {
		return x.TempType
	}
	return 0
}

type RecPositionOpsResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *RecPositionOpsResp) Reset() {
	*x = RecPositionOpsResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cp_drama_admin_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecPositionOpsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecPositionOpsResp) ProtoMessage() {}

func (x *RecPositionOpsResp) ProtoReflect() protoreflect.Message {
	mi := &file_cp_drama_admin_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecPositionOpsResp.ProtoReflect.Descriptor instead.
func (*RecPositionOpsResp) Descriptor() ([]byte, []int) {
	return file_cp_drama_admin_proto_rawDescGZIP(), []int{21}
}

func (x *RecPositionOpsResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CollDramaReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid    string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Did    int64  `protobuf:"varint,2,opt,name=did,proto3" json:"did,omitempty"`
	Status int64  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *CollDramaReq) Reset() {
	*x = CollDramaReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cp_drama_admin_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CollDramaReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollDramaReq) ProtoMessage() {}

func (x *CollDramaReq) ProtoReflect() protoreflect.Message {
	mi := &file_cp_drama_admin_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollDramaReq.ProtoReflect.Descriptor instead.
func (*CollDramaReq) Descriptor() ([]byte, []int) {
	return file_cp_drama_admin_proto_rawDescGZIP(), []int{22}
}

func (x *CollDramaReq) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *CollDramaReq) GetDid() int64 {
	if x != nil {
		return x.Did
	}
	return 0
}

func (x *CollDramaReq) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

type CheckCollDramaReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Did int64  `protobuf:"varint,2,opt,name=did,proto3" json:"did,omitempty"`
}

func (x *CheckCollDramaReq) Reset() {
	*x = CheckCollDramaReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cp_drama_admin_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckCollDramaReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckCollDramaReq) ProtoMessage() {}

func (x *CheckCollDramaReq) ProtoReflect() protoreflect.Message {
	mi := &file_cp_drama_admin_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckCollDramaReq.ProtoReflect.Descriptor instead.
func (*CheckCollDramaReq) Descriptor() ([]byte, []int) {
	return file_cp_drama_admin_proto_rawDescGZIP(), []int{23}
}

func (x *CheckCollDramaReq) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *CheckCollDramaReq) GetDid() int64 {
	if x != nil {
		return x.Did
	}
	return 0
}

type CheckCollDramaResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsFollow int64 `protobuf:"varint,1,opt,name=is_follow,json=isFollow,proto3" json:"is_follow,omitempty"`
}

func (x *CheckCollDramaResp) Reset() {
	*x = CheckCollDramaResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cp_drama_admin_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckCollDramaResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckCollDramaResp) ProtoMessage() {}

func (x *CheckCollDramaResp) ProtoReflect() protoreflect.Message {
	mi := &file_cp_drama_admin_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckCollDramaResp.ProtoReflect.Descriptor instead.
func (*CheckCollDramaResp) Descriptor() ([]byte, []int) {
	return file_cp_drama_admin_proto_rawDescGZIP(), []int{24}
}

func (x *CheckCollDramaResp) GetIsFollow() int64 {
	if x != nil {
		return x.IsFollow
	}
	return 0
}

var File_cp_drama_admin_proto protoreflect.FileDescriptor

var file_cp_drama_admin_proto_rawDesc = []byte{
	0x0a, 0x14, 0x63, 0x70, 0x5f, 0x64, 0x72, 0x61, 0x6d, 0x61, 0x5f, 0x61, 0x64, 0x6d, 0x69, 0x6e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x63, 0x70, 0x22, 0x05, 0x0a, 0x03, 0x52, 0x65,
	0x71, 0x22, 0x06, 0x0a, 0x04, 0x52, 0x65, 0x73, 0x70, 0x22, 0x1e, 0x0a, 0x0c, 0x44, 0x72, 0x61,
	0x6d, 0x61, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x34, 0x0a, 0x0d, 0x44, 0x72, 0x61,
	0x6d, 0x61, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x12, 0x23, 0x0a, 0x05, 0x64, 0x72,
	0x61, 0x6d, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x63, 0x70, 0x2e, 0x44,
	0x72, 0x61, 0x6d, 0x61, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x64, 0x72, 0x61, 0x6d, 0x61, 0x22,
	0x25, 0x0a, 0x11, 0x44, 0x72, 0x61, 0x6d, 0x61, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x69, 0x64, 0x73, 0x22, 0x38, 0x0a, 0x12, 0x44, 0x72, 0x61, 0x6d, 0x61, 0x53,
	0x68, 0x6f, 0x72, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x22, 0x0a, 0x04,
	0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x63, 0x70, 0x2e,
	0x44, 0x72, 0x61, 0x6d, 0x61, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74,
	0x22, 0xc4, 0x05, 0x0a, 0x09, 0x44, 0x72, 0x61, 0x6d, 0x61, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63,
	0x6f, 0x76, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x75, 0x74, 0x68,
	0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72,
	0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x1d, 0x0a, 0x0a,
	0x63, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x09, 0x63, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6e,
	0x69, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x6e, 0x69, 0x64, 0x12, 0x1f, 0x0a,
	0x0b, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0a, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x72, 0x49, 0x64, 0x12, 0x23,
	0x0a, 0x0d, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x72, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x18, 0x0a,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x12, 0x1f, 0x0a,
	0x0b, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x5f, 0x69, 0x6e, 0x74, 0x72, 0x6f, 0x18, 0x0b, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x49, 0x6e, 0x74, 0x72, 0x6f, 0x12, 0x14,
	0x0a, 0x05, 0x69, 0x6e, 0x74, 0x72, 0x6f, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69,
	0x6e, 0x74, 0x72, 0x6f, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x70, 0x72,
	0x69, 0x63, 0x65, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x69, 0x73, 0x5f, 0x70, 0x61, 0x79, 0x18,
	0x0e, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x69, 0x73, 0x50, 0x61, 0x79, 0x12, 0x1b, 0x0a, 0x09,
	0x70, 0x61, 0x79, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x08, 0x70, 0x61, 0x79, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69,
	0x63, 0x65, 0x18, 0x10, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12,
	0x21, 0x0a, 0x0c, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x61, 0x6c, 0x6c, 0x18,
	0x11, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x41,
	0x6c, 0x6c, 0x12, 0x2c, 0x0a, 0x12, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x61,
	0x6c, 0x6c, 0x5f, 0x65, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x12, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10,
	0x64, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x41, 0x6c, 0x6c, 0x45, 0x74, 0x69, 0x6d, 0x65,
	0x12, 0x27, 0x0a, 0x0f, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x73, 0x69, 0x6e,
	0x67, 0x6c, 0x65, 0x18, 0x13, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0e, 0x64, 0x69, 0x73, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x12, 0x32, 0x0a, 0x15, 0x64, 0x69, 0x73,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x73, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x5f, 0x65, 0x74, 0x69,
	0x6d, 0x65, 0x18, 0x14, 0x20, 0x01, 0x28, 0x09, 0x52, 0x13, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x45, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x15, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x25, 0x0a, 0x0e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f,
	0x64, 0x69, 0x76, 0x69, 0x64, 0x65, 0x64, 0x18, 0x16, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x44, 0x69, 0x76, 0x69, 0x64, 0x65, 0x64, 0x12, 0x29, 0x0a, 0x10,
	0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x72, 0x5f, 0x64, 0x69, 0x76, 0x69, 0x64, 0x65, 0x64,
	0x18, 0x17, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x72,
	0x44, 0x69, 0x76, 0x69, 0x64, 0x65, 0x64, 0x22, 0x95, 0x01, 0x0a, 0x0a, 0x44, 0x72, 0x61, 0x6d,
	0x61, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x74, 0x72,
	0x6f, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x6e, 0x74, 0x72, 0x6f, 0x12, 0x1f,
	0x0a, 0x0b, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x5f, 0x69, 0x6e, 0x74, 0x72, 0x6f, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x49, 0x6e, 0x74, 0x72, 0x6f, 0x22,
	0x8b, 0x01, 0x0a, 0x08, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x75,
	0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x61,
	0x72, 0x6b, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6d, 0x61, 0x72, 0x6b, 0x12, 0x1d,
	0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x73, 0x0a,
	0x0f, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x72, 0x45, 0x64, 0x69, 0x74, 0x52, 0x65, 0x71,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12,
	0x0a, 0x04, 0x6d, 0x61, 0x72, 0x6b, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6d, 0x61,
	0x72, 0x6b, 0x22, 0x22, 0x0a, 0x10, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x72, 0x45, 0x64,
	0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x38, 0x0a, 0x10, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x65, 0x72, 0x44, 0x69, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x24, 0x0a, 0x04, 0x6c, 0x69,
	0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x63, 0x70, 0x2e, 0x50, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x65, 0x72, 0x44, 0x69, 0x63, 0x74, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74,
	0x22, 0x26, 0x0a, 0x0e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x72, 0x41, 0x6c, 0x6c, 0x52,
	0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x05, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x22, 0x32, 0x0a, 0x0c, 0x50, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x65, 0x72, 0x44, 0x69, 0x63, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x33, 0x0a, 0x0f,
	0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x72, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x20, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e,
	0x63, 0x70, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x72, 0x52, 0x04, 0x6c, 0x69, 0x73,
	0x74, 0x22, 0xd4, 0x01, 0x0a, 0x0b, 0x52, 0x65, 0x63, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x65, 0x6d, 0x70, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x74, 0x65, 0x6d, 0x70, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x6f, 0x72, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x04, 0x73, 0x6f, 0x72, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x6f, 0x76, 0x65, 0x6c, 0x5f,
	0x69, 0x64, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x6f, 0x76, 0x65, 0x6c,
	0x49, 0x64, 0x73, 0x12, 0x15, 0x0a, 0x06, 0x69, 0x73, 0x5f, 0x64, 0x65, 0x6c, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x05, 0x69, 0x73, 0x44, 0x65, 0x6c, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x42, 0x0a, 0x0e, 0x52, 0x65, 0x63, 0x50,
	0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69,
	0x6d, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74,
	0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x22, 0x36, 0x0a, 0x0f,
	0x52, 0x65, 0x63, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x23, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e,
	0x63, 0x70, 0x2e, 0x52, 0x65, 0x63, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x04,
	0x6c, 0x69, 0x73, 0x74, 0x22, 0x23, 0x0a, 0x11, 0x52, 0x65, 0x63, 0x50, 0x6f, 0x73, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x4f, 0x70, 0x73, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x86, 0x01, 0x0a, 0x12, 0x52, 0x65,
	0x63, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x6f, 0x76, 0x65, 0x6c, 0x5f, 0x69, 0x64,
	0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x6f, 0x76, 0x65, 0x6c, 0x49, 0x64,
	0x73, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x6f, 0x72, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x04, 0x73, 0x6f, 0x72, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x65, 0x6d, 0x70, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x74, 0x65, 0x6d, 0x70, 0x54, 0x79,
	0x70, 0x65, 0x22, 0x75, 0x0a, 0x11, 0x52, 0x65, 0x63, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x41, 0x64, 0x64, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6e,
	0x6f, 0x76, 0x65, 0x6c, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x6e, 0x6f, 0x76, 0x65, 0x6c, 0x49, 0x64, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x6f, 0x72, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x73, 0x6f, 0x72, 0x74, 0x12, 0x1b, 0x0a, 0x09,
	0x74, 0x65, 0x6d, 0x70, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x08, 0x74, 0x65, 0x6d, 0x70, 0x54, 0x79, 0x70, 0x65, 0x22, 0x24, 0x0a, 0x12, 0x52, 0x65, 0x63,
	0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x4f, 0x70, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x4a, 0x0a, 0x0c, 0x43, 0x6f, 0x6c, 0x6c, 0x44, 0x72, 0x61, 0x6d, 0x61, 0x52, 0x65, 0x71, 0x12,
	0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69,
	0x64, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03,
	0x64, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x37, 0x0a, 0x11, 0x43,
	0x68, 0x65, 0x63, 0x6b, 0x43, 0x6f, 0x6c, 0x6c, 0x44, 0x72, 0x61, 0x6d, 0x61, 0x52, 0x65, 0x71,
	0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75,
	0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x64, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x03, 0x64, 0x69, 0x64, 0x22, 0x31, 0x0a, 0x12, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x43, 0x6f, 0x6c,
	0x6c, 0x44, 0x72, 0x61, 0x6d, 0x61, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x73,
	0x5f, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x69,
	0x73, 0x46, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x32, 0x90, 0x05, 0x0a, 0x05, 0x44, 0x72, 0x61, 0x6d,
	0x61, 0x12, 0x30, 0x0a, 0x09, 0x44, 0x72, 0x61, 0x6d, 0x61, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x10,
	0x2e, 0x63, 0x70, 0x2e, 0x44, 0x72, 0x61, 0x6d, 0x61, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71,
	0x1a, 0x11, 0x2e, 0x63, 0x70, 0x2e, 0x44, 0x72, 0x61, 0x6d, 0x61, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x37, 0x0a, 0x0c, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x72, 0x4c,
	0x69, 0x73, 0x74, 0x12, 0x12, 0x2e, 0x63, 0x70, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65,
	0x72, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e, 0x63, 0x70, 0x2e, 0x50, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x65, 0x72, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2d, 0x0a, 0x0c,
	0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x72, 0x44, 0x69, 0x63, 0x74, 0x12, 0x07, 0x2e, 0x63,
	0x70, 0x2e, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x63, 0x70, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x65, 0x72, 0x44, 0x69, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x39, 0x0a, 0x0c, 0x50,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x72, 0x45, 0x64, 0x69, 0x74, 0x12, 0x13, 0x2e, 0x63, 0x70,
	0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x72, 0x45, 0x64, 0x69, 0x74, 0x52, 0x65, 0x71,
	0x1a, 0x14, 0x2e, 0x63, 0x70, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x65, 0x72, 0x45, 0x64,
	0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x3a, 0x0a, 0x0f, 0x52, 0x65, 0x63, 0x50, 0x6f, 0x73,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x12, 0x2e, 0x63, 0x70, 0x2e, 0x52,
	0x65, 0x63, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e,
	0x63, 0x70, 0x2e, 0x52, 0x65, 0x63, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x3f, 0x0a, 0x0e, 0x52, 0x65, 0x63, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x41, 0x64, 0x64, 0x12, 0x15, 0x2e, 0x63, 0x70, 0x2e, 0x52, 0x65, 0x63, 0x50, 0x6f, 0x73,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x64, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x63, 0x70,
	0x2e, 0x52, 0x65, 0x63, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x4f, 0x70, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x41, 0x0a, 0x0f, 0x52, 0x65, 0x63, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x45, 0x64, 0x69, 0x74, 0x12, 0x16, 0x2e, 0x63, 0x70, 0x2e, 0x52, 0x65, 0x63, 0x50,
	0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x1a, 0x16,
	0x2e, 0x63, 0x70, 0x2e, 0x52, 0x65, 0x63, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x4f,
	0x70, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x3f, 0x0a, 0x0e, 0x52, 0x65, 0x63, 0x50, 0x6f, 0x73,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x65, 0x6c, 0x12, 0x15, 0x2e, 0x63, 0x70, 0x2e, 0x52, 0x65,
	0x63, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x4f, 0x70, 0x73, 0x52, 0x65, 0x71, 0x1a,
	0x16, 0x2e, 0x63, 0x70, 0x2e, 0x52, 0x65, 0x63, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x4f, 0x70, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x3f, 0x0a, 0x0e, 0x44, 0x72, 0x61, 0x6d, 0x61,
	0x53, 0x68, 0x6f, 0x72, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x15, 0x2e, 0x63, 0x70, 0x2e, 0x44,
	0x72, 0x61, 0x6d, 0x61, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71,
	0x1a, 0x16, 0x2e, 0x63, 0x70, 0x2e, 0x44, 0x72, 0x61, 0x6d, 0x61, 0x53, 0x68, 0x6f, 0x72, 0x74,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x2b, 0x0a, 0x0d, 0x55, 0x73, 0x65, 0x72,
	0x43, 0x6f, 0x6c, 0x6c, 0x44, 0x72, 0x61, 0x6d, 0x61, 0x12, 0x10, 0x2e, 0x63, 0x70, 0x2e, 0x43,
	0x6f, 0x6c, 0x6c, 0x44, 0x72, 0x61, 0x6d, 0x61, 0x52, 0x65, 0x71, 0x1a, 0x08, 0x2e, 0x63, 0x70,
	0x2e, 0x52, 0x65, 0x73, 0x70, 0x12, 0x43, 0x0a, 0x12, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x55, 0x73,
	0x65, 0x72, 0x43, 0x6f, 0x6c, 0x6c, 0x44, 0x72, 0x61, 0x6d, 0x61, 0x12, 0x15, 0x2e, 0x63, 0x70,
	0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x43, 0x6f, 0x6c, 0x6c, 0x44, 0x72, 0x61, 0x6d, 0x61, 0x52,
	0x65, 0x71, 0x1a, 0x16, 0x2e, 0x63, 0x70, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x43, 0x6f, 0x6c,
	0x6c, 0x44, 0x72, 0x61, 0x6d, 0x61, 0x52, 0x65, 0x73, 0x70, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f,
	0x64, 0x72, 0x61, 0x6d, 0x61, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cp_drama_admin_proto_rawDescOnce sync.Once
	file_cp_drama_admin_proto_rawDescData = file_cp_drama_admin_proto_rawDesc
)

func file_cp_drama_admin_proto_rawDescGZIP() []byte {
	file_cp_drama_admin_proto_rawDescOnce.Do(func() {
		file_cp_drama_admin_proto_rawDescData = protoimpl.X.CompressGZIP(file_cp_drama_admin_proto_rawDescData)
	})
	return file_cp_drama_admin_proto_rawDescData
}

var file_cp_drama_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_cp_drama_admin_proto_goTypes = []interface{}{
	(*Req)(nil),                // 0: cp.Req
	(*Resp)(nil),               // 1: cp.Resp
	(*DramaInfoReq)(nil),       // 2: cp.DramaInfoReq
	(*DramaInfoResp)(nil),      // 3: cp.DramaInfoResp
	(*DramaShortListReq)(nil),  // 4: cp.DramaShortListReq
	(*DramaShortListResp)(nil), // 5: cp.DramaShortListResp
	(*DramaInfo)(nil),          // 6: cp.DramaInfo
	(*DramaShort)(nil),         // 7: cp.DramaShort
	(*Producer)(nil),           // 8: cp.Producer
	(*ProducerEditReq)(nil),    // 9: cp.ProducerEditReq
	(*ProducerEditResp)(nil),   // 10: cp.ProducerEditResp
	(*ProducerDictResp)(nil),   // 11: cp.ProducerDictResp
	(*ProducerAllReq)(nil),     // 12: cp.ProducerAllReq
	(*ProducerDict)(nil),       // 13: cp.ProducerDict
	(*ProducerAllResp)(nil),    // 14: cp.ProducerAllResp
	(*RecPosition)(nil),        // 15: cp.RecPosition
	(*RecPositionReq)(nil),     // 16: cp.RecPositionReq
	(*RecPositionResp)(nil),    // 17: cp.RecPositionResp
	(*RecPositionOpsReq)(nil),  // 18: cp.RecPositionOpsReq
	(*RecPositionDataReq)(nil), // 19: cp.RecPositionDataReq
	(*RecPositionAddReq)(nil),  // 20: cp.RecPositionAddReq
	(*RecPositionOpsResp)(nil), // 21: cp.RecPositionOpsResp
	(*CollDramaReq)(nil),       // 22: cp.CollDramaReq
	(*CheckCollDramaReq)(nil),  // 23: cp.CheckCollDramaReq
	(*CheckCollDramaResp)(nil), // 24: cp.CheckCollDramaResp
}
var file_cp_drama_admin_proto_depIdxs = []int32{
	6,  // 0: cp.DramaInfoResp.drama:type_name -> cp.DramaInfo
	7,  // 1: cp.DramaShortListResp.list:type_name -> cp.DramaShort
	13, // 2: cp.ProducerDictResp.list:type_name -> cp.ProducerDict
	8,  // 3: cp.ProducerAllResp.list:type_name -> cp.Producer
	15, // 4: cp.RecPositionResp.list:type_name -> cp.RecPosition
	2,  // 5: cp.Drama.DramaInfo:input_type -> cp.DramaInfoReq
	12, // 6: cp.Drama.ProducerList:input_type -> cp.ProducerAllReq
	0,  // 7: cp.Drama.ProducerDict:input_type -> cp.Req
	9,  // 8: cp.Drama.ProducerEdit:input_type -> cp.ProducerEditReq
	16, // 9: cp.Drama.RecPositionList:input_type -> cp.RecPositionReq
	20, // 10: cp.Drama.RecPositionAdd:input_type -> cp.RecPositionAddReq
	19, // 11: cp.Drama.RecPositionEdit:input_type -> cp.RecPositionDataReq
	18, // 12: cp.Drama.RecPositionDel:input_type -> cp.RecPositionOpsReq
	4,  // 13: cp.Drama.DramaShortList:input_type -> cp.DramaShortListReq
	22, // 14: cp.Drama.UserCollDrama:input_type -> cp.CollDramaReq
	23, // 15: cp.Drama.CheckUserCollDrama:input_type -> cp.CheckCollDramaReq
	3,  // 16: cp.Drama.DramaInfo:output_type -> cp.DramaInfoResp
	14, // 17: cp.Drama.ProducerList:output_type -> cp.ProducerAllResp
	11, // 18: cp.Drama.ProducerDict:output_type -> cp.ProducerDictResp
	10, // 19: cp.Drama.ProducerEdit:output_type -> cp.ProducerEditResp
	17, // 20: cp.Drama.RecPositionList:output_type -> cp.RecPositionResp
	21, // 21: cp.Drama.RecPositionAdd:output_type -> cp.RecPositionOpsResp
	21, // 22: cp.Drama.RecPositionEdit:output_type -> cp.RecPositionOpsResp
	21, // 23: cp.Drama.RecPositionDel:output_type -> cp.RecPositionOpsResp
	5,  // 24: cp.Drama.DramaShortList:output_type -> cp.DramaShortListResp
	1,  // 25: cp.Drama.UserCollDrama:output_type -> cp.Resp
	24, // 26: cp.Drama.CheckUserCollDrama:output_type -> cp.CheckCollDramaResp
	16, // [16:27] is the sub-list for method output_type
	5,  // [5:16] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_cp_drama_admin_proto_init() }
func file_cp_drama_admin_proto_init() {
	if File_cp_drama_admin_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cp_drama_admin_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Req); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cp_drama_admin_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Resp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cp_drama_admin_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DramaInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cp_drama_admin_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DramaInfoResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cp_drama_admin_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DramaShortListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cp_drama_admin_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DramaShortListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cp_drama_admin_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DramaInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cp_drama_admin_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DramaShort); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cp_drama_admin_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Producer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cp_drama_admin_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProducerEditReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cp_drama_admin_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProducerEditResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cp_drama_admin_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProducerDictResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cp_drama_admin_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProducerAllReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cp_drama_admin_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProducerDict); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cp_drama_admin_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProducerAllResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cp_drama_admin_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecPosition); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cp_drama_admin_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecPositionReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cp_drama_admin_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecPositionResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cp_drama_admin_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecPositionOpsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cp_drama_admin_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecPositionDataReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cp_drama_admin_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecPositionAddReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cp_drama_admin_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecPositionOpsResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cp_drama_admin_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CollDramaReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cp_drama_admin_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckCollDramaReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cp_drama_admin_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckCollDramaResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cp_drama_admin_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cp_drama_admin_proto_goTypes,
		DependencyIndexes: file_cp_drama_admin_proto_depIdxs,
		MessageInfos:      file_cp_drama_admin_proto_msgTypes,
	}.Build()
	File_cp_drama_admin_proto = out.File
	file_cp_drama_admin_proto_rawDesc = nil
	file_cp_drama_admin_proto_goTypes = nil
	file_cp_drama_admin_proto_depIdxs = nil
}
