// Code generated by goctl. DO NOT EDIT.
// Source: cp_drama_admin.proto

package server

import (
	"context"

	"audio/apps/rpc/drama/drama"
	"audio/apps/rpc/drama/internal/logic"
	"audio/apps/rpc/drama/internal/svc"
)

type DramaServer struct {
	svcCtx *svc.ServiceContext
	drama.UnimplementedDramaServer
}

func NewDramaServer(svcCtx *svc.ServiceContext) *DramaServer {
	return &DramaServer{
		svcCtx: svcCtx,
	}
}

// 后台-有声作品详情
func (s *DramaServer) DramaInfo(ctx context.Context, in *drama.DramaInfoReq) (*drama.DramaInfoResp, error) {
	l := logic.NewDramaInfoLogic(ctx, s.svcCtx)
	return l.DramaInfo(in)
}

// 后台 - 全部工作室列表
func (s *DramaServer) ProducerList(ctx context.Context, in *drama.ProducerAllReq) (*drama.ProducerAllResp, error) {
	l := logic.NewProducerListLogic(ctx, s.svcCtx)
	return l.ProducerList(in)
}

func (s *DramaServer) ProducerDict(ctx context.Context, in *drama.Req) (*drama.ProducerDictResp, error) {
	l := logic.NewProducerDictLogic(ctx, s.svcCtx)
	return l.ProducerDict(in)
}

func (s *DramaServer) ProducerEdit(ctx context.Context, in *drama.ProducerEditReq) (*drama.ProducerEditResp, error) {
	l := logic.NewProducerEditLogic(ctx, s.svcCtx)
	return l.ProducerEdit(in)
}

// 后台 - 有声推荐列表
func (s *DramaServer) RecPositionList(ctx context.Context, in *drama.RecPositionReq) (*drama.RecPositionResp, error) {
	l := logic.NewRecPositionListLogic(ctx, s.svcCtx)
	return l.RecPositionList(in)
}

func (s *DramaServer) RecPositionAdd(ctx context.Context, in *drama.RecPositionAddReq) (*drama.RecPositionOpsResp, error) {
	l := logic.NewRecPositionAddLogic(ctx, s.svcCtx)
	return l.RecPositionAdd(in)
}

func (s *DramaServer) RecPositionEdit(ctx context.Context, in *drama.RecPositionDataReq) (*drama.RecPositionOpsResp, error) {
	l := logic.NewRecPositionEditLogic(ctx, s.svcCtx)
	return l.RecPositionEdit(in)
}

func (s *DramaServer) RecPositionDel(ctx context.Context, in *drama.RecPositionOpsReq) (*drama.RecPositionOpsResp, error) {
	l := logic.NewRecPositionDelLogic(ctx, s.svcCtx)
	return l.RecPositionDel(in)
}

// 公共部分
func (s *DramaServer) DramaShortList(ctx context.Context, in *drama.DramaShortListReq) (*drama.DramaShortListResp, error) {
	l := logic.NewDramaShortListLogic(ctx, s.svcCtx)
	return l.DramaShortList(in)
}

func (s *DramaServer) UserCollDrama(ctx context.Context, in *drama.CollDramaReq) (*drama.Resp, error) {
	l := logic.NewUserCollDramaLogic(ctx, s.svcCtx)
	return l.UserCollDrama(in)
}

func (s *DramaServer) CheckUserCollDrama(ctx context.Context, in *drama.CheckCollDramaReq) (*drama.CheckCollDramaResp, error) {
	l := logic.NewCheckUserCollDramaLogic(ctx, s.svcCtx)
	return l.CheckUserCollDrama(in)
}
