// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: message/admin.proto

package cp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AdminCommon_Sort int32

const (
	AdminCommon_SortAsc  AdminCommon_Sort = 0
	AdminCommon_SortDesc AdminCommon_Sort = 1
)

// Enum value maps for AdminCommon_Sort.
var (
	AdminCommon_Sort_name = map[int32]string{
		0: "SortAsc",
		1: "SortDesc",
	}
	AdminCommon_Sort_value = map[string]int32{
		"SortAsc":  0,
		"SortDesc": 1,
	}
)

func (x AdminCommon_Sort) Enum() *AdminCommon_Sort {
	p := new(AdminCommon_Sort)
	*p = x
	return p
}

func (x AdminCommon_Sort) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AdminCommon_Sort) Descriptor() protoreflect.EnumDescriptor {
	return file_message_admin_proto_enumTypes[0].Descriptor()
}

func (AdminCommon_Sort) Type() protoreflect.EnumType {
	return &file_message_admin_proto_enumTypes[0]
}

func (x AdminCommon_Sort) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AdminCommon_Sort.Descriptor instead.
func (AdminCommon_Sort) EnumDescriptor() ([]byte, []int) {
	return file_message_admin_proto_rawDescGZIP(), []int{0, 0}
}

type AdminCommon_SqlOperator int32

const (
	// =
	AdminCommon_SqlOperatorEQ AdminCommon_SqlOperator = 0
	// !=
	AdminCommon_SqlOperatorNE AdminCommon_SqlOperator = 1
	// >
	AdminCommon_SqlOperatorGT AdminCommon_SqlOperator = 2
	// >=
	AdminCommon_SqlOperatorGE AdminCommon_SqlOperator = 3
	// <
	AdminCommon_SqlOperatorLT AdminCommon_SqlOperator = 4
	// <=
	AdminCommon_SqlOperatorLE AdminCommon_SqlOperator = 5
	// IN
	AdminCommon_SqlOperatorIn AdminCommon_SqlOperator = 6
	// NOT IN
	AdminCommon_SqlOperatorNotIn AdminCommon_SqlOperator = 7
	// FIND_IN_SET
	AdminCommon_SqlOperatorFindInSet AdminCommon_SqlOperator = 8
	// LIKE %{}%
	AdminCommon_SqlOperatorLike AdminCommon_SqlOperator = 9
	// LIKE {}%
	AdminCommon_SqlOperatorLikeLeft AdminCommon_SqlOperator = 10
	// LIKE %{}
	AdminCommon_SqlOperatorLikeRight AdminCommon_SqlOperator = 11
	// NOT LIKE %{}%
	AdminCommon_SqlOperatorNotLike AdminCommon_SqlOperator = 12
	// NOT LIKE {}%
	AdminCommon_SqlOperatorNotLikeLeft AdminCommon_SqlOperator = 13
	// NOT LIKE %{}
	AdminCommon_SqlOperatorNotLikeRight AdminCommon_SqlOperator = 14
)

// Enum value maps for AdminCommon_SqlOperator.
var (
	AdminCommon_SqlOperator_name = map[int32]string{
		0:  "SqlOperatorEQ",
		1:  "SqlOperatorNE",
		2:  "SqlOperatorGT",
		3:  "SqlOperatorGE",
		4:  "SqlOperatorLT",
		5:  "SqlOperatorLE",
		6:  "SqlOperatorIn",
		7:  "SqlOperatorNotIn",
		8:  "SqlOperatorFindInSet",
		9:  "SqlOperatorLike",
		10: "SqlOperatorLikeLeft",
		11: "SqlOperatorLikeRight",
		12: "SqlOperatorNotLike",
		13: "SqlOperatorNotLikeLeft",
		14: "SqlOperatorNotLikeRight",
	}
	AdminCommon_SqlOperator_value = map[string]int32{
		"SqlOperatorEQ":           0,
		"SqlOperatorNE":           1,
		"SqlOperatorGT":           2,
		"SqlOperatorGE":           3,
		"SqlOperatorLT":           4,
		"SqlOperatorLE":           5,
		"SqlOperatorIn":           6,
		"SqlOperatorNotIn":        7,
		"SqlOperatorFindInSet":    8,
		"SqlOperatorLike":         9,
		"SqlOperatorLikeLeft":     10,
		"SqlOperatorLikeRight":    11,
		"SqlOperatorNotLike":      12,
		"SqlOperatorNotLikeLeft":  13,
		"SqlOperatorNotLikeRight": 14,
	}
)

func (x AdminCommon_SqlOperator) Enum() *AdminCommon_SqlOperator {
	p := new(AdminCommon_SqlOperator)
	*p = x
	return p
}

func (x AdminCommon_SqlOperator) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AdminCommon_SqlOperator) Descriptor() protoreflect.EnumDescriptor {
	return file_message_admin_proto_enumTypes[1].Descriptor()
}

func (AdminCommon_SqlOperator) Type() protoreflect.EnumType {
	return &file_message_admin_proto_enumTypes[1]
}

func (x AdminCommon_SqlOperator) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AdminCommon_SqlOperator.Descriptor instead.
func (AdminCommon_SqlOperator) EnumDescriptor() ([]byte, []int) {
	return file_message_admin_proto_rawDescGZIP(), []int{0, 1}
}

type AdminCommon struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AdminCommon) Reset() {
	*x = AdminCommon{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_admin_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdminCommon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminCommon) ProtoMessage() {}

func (x *AdminCommon) ProtoReflect() protoreflect.Message {
	mi := &file_message_admin_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminCommon.ProtoReflect.Descriptor instead.
func (*AdminCommon) Descriptor() ([]byte, []int) {
	return file_message_admin_proto_rawDescGZIP(), []int{0}
}

type AdminCommon_ListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page          uint32           `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         uint32           `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	SearchType    string           `protobuf:"bytes,3,opt,name=search_type,json=searchType,proto3" json:"search_type,omitempty"`
	SearchKeyword string           `protobuf:"bytes,4,opt,name=search_keyword,json=searchKeyword,proto3" json:"search_keyword,omitempty"`
	OrderField    string           `protobuf:"bytes,5,opt,name=order_field,json=orderField,proto3" json:"order_field,omitempty"`
	OrderSort     AdminCommon_Sort `protobuf:"varint,6,opt,name=order_sort,json=orderSort,proto3,enum=cp.AdminCommon_Sort" json:"order_sort,omitempty"`
}

func (x *AdminCommon_ListReq) Reset() {
	*x = AdminCommon_ListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_admin_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdminCommon_ListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminCommon_ListReq) ProtoMessage() {}

func (x *AdminCommon_ListReq) ProtoReflect() protoreflect.Message {
	mi := &file_message_admin_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminCommon_ListReq.ProtoReflect.Descriptor instead.
func (*AdminCommon_ListReq) Descriptor() ([]byte, []int) {
	return file_message_admin_proto_rawDescGZIP(), []int{0, 0}
}

func (x *AdminCommon_ListReq) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *AdminCommon_ListReq) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *AdminCommon_ListReq) GetSearchType() string {
	if x != nil {
		return x.SearchType
	}
	return ""
}

func (x *AdminCommon_ListReq) GetSearchKeyword() string {
	if x != nil {
		return x.SearchKeyword
	}
	return ""
}

func (x *AdminCommon_ListReq) GetOrderField() string {
	if x != nil {
		return x.OrderField
	}
	return ""
}

func (x *AdminCommon_ListReq) GetOrderSort() AdminCommon_Sort {
	if x != nil {
		return x.OrderSort
	}
	return AdminCommon_SortAsc
}

// 多级筛选结构
type AdminCommon_CascadeFilterRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filters []*AdminCommon_CascadeFilterRes_Option `protobuf:"bytes,1,rep,name=filters,proto3" json:"filters,omitempty"`
}

func (x *AdminCommon_CascadeFilterRes) Reset() {
	*x = AdminCommon_CascadeFilterRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_admin_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdminCommon_CascadeFilterRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminCommon_CascadeFilterRes) ProtoMessage() {}

func (x *AdminCommon_CascadeFilterRes) ProtoReflect() protoreflect.Message {
	mi := &file_message_admin_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminCommon_CascadeFilterRes.ProtoReflect.Descriptor instead.
func (*AdminCommon_CascadeFilterRes) Descriptor() ([]byte, []int) {
	return file_message_admin_proto_rawDescGZIP(), []int{0, 1}
}

func (x *AdminCommon_CascadeFilterRes) GetFilters() []*AdminCommon_CascadeFilterRes_Option {
	if x != nil {
		return x.Filters
	}
	return nil
}

type AdminCommon_CascadeFilterRes_Option struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value    uint32                                 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	Label    string                                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Children []*AdminCommon_CascadeFilterRes_Option `protobuf:"bytes,3,rep,name=children,proto3" json:"children,omitempty"`
}

func (x *AdminCommon_CascadeFilterRes_Option) Reset() {
	*x = AdminCommon_CascadeFilterRes_Option{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_admin_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdminCommon_CascadeFilterRes_Option) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminCommon_CascadeFilterRes_Option) ProtoMessage() {}

func (x *AdminCommon_CascadeFilterRes_Option) ProtoReflect() protoreflect.Message {
	mi := &file_message_admin_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminCommon_CascadeFilterRes_Option.ProtoReflect.Descriptor instead.
func (*AdminCommon_CascadeFilterRes_Option) Descriptor() ([]byte, []int) {
	return file_message_admin_proto_rawDescGZIP(), []int{0, 1, 0}
}

func (x *AdminCommon_CascadeFilterRes_Option) GetValue() uint32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *AdminCommon_CascadeFilterRes_Option) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *AdminCommon_CascadeFilterRes_Option) GetChildren() []*AdminCommon_CascadeFilterRes_Option {
	if x != nil {
		return x.Children
	}
	return nil
}

var File_message_admin_proto protoreflect.FileDescriptor

var file_message_admin_proto_rawDesc = []byte{
	0x0a, 0x13, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x63, 0x70, 0x22, 0xb5, 0x06, 0x0a, 0x0b, 0x41, 0x64,
	0x6d, 0x69, 0x6e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x1a, 0xd1, 0x01, 0x0a, 0x07, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d,
	0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12,
	0x1f, 0x0a, 0x0b, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x25, 0x0a, 0x0e, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x5f, 0x6b, 0x65, 0x79, 0x77, 0x6f,
	0x72, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68,
	0x4b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x6f, 0x72, 0x64, 0x65, 0x72,
	0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6f, 0x72,
	0x64, 0x65, 0x72, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x33, 0x0a, 0x0a, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x5f, 0x73, 0x6f, 0x72, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x63,
	0x70, 0x2e, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x53, 0x6f,
	0x72, 0x74, 0x52, 0x09, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x6f, 0x72, 0x74, 0x1a, 0xd0, 0x01,
	0x0a, 0x10, 0x43, 0x61, 0x73, 0x63, 0x61, 0x64, 0x65, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x12, 0x41, 0x0a, 0x07, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x63, 0x70, 0x2e, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x43, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x43, 0x61, 0x73, 0x63, 0x61, 0x64, 0x65, 0x46, 0x69, 0x6c, 0x74,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x2e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x07, 0x66, 0x69,
	0x6c, 0x74, 0x65, 0x72, 0x73, 0x1a, 0x79, 0x0a, 0x06, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x12, 0x43, 0x0a, 0x08, 0x63,
	0x68, 0x69, 0x6c, 0x64, 0x72, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x27, 0x2e,
	0x63, 0x70, 0x2e, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x43,
	0x61, 0x73, 0x63, 0x61, 0x64, 0x65, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x2e,
	0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x63, 0x68, 0x69, 0x6c, 0x64, 0x72, 0x65, 0x6e,
	0x22, 0x21, 0x0a, 0x04, 0x53, 0x6f, 0x72, 0x74, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x6f, 0x72, 0x74,
	0x41, 0x73, 0x63, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x53, 0x6f, 0x72, 0x74, 0x44, 0x65, 0x73,
	0x63, 0x10, 0x01, 0x22, 0xdb, 0x02, 0x0a, 0x0b, 0x53, 0x71, 0x6c, 0x4f, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x6f, 0x72, 0x12, 0x11, 0x0a, 0x0d, 0x53, 0x71, 0x6c, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74,
	0x6f, 0x72, 0x45, 0x51, 0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d, 0x53, 0x71, 0x6c, 0x4f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x6f, 0x72, 0x4e, 0x45, 0x10, 0x01, 0x12, 0x11, 0x0a, 0x0d, 0x53, 0x71, 0x6c,
	0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x47, 0x54, 0x10, 0x02, 0x12, 0x11, 0x0a, 0x0d,
	0x53, 0x71, 0x6c, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x47, 0x45, 0x10, 0x03, 0x12,
	0x11, 0x0a, 0x0d, 0x53, 0x71, 0x6c, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x4c, 0x54,
	0x10, 0x04, 0x12, 0x11, 0x0a, 0x0d, 0x53, 0x71, 0x6c, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f,
	0x72, 0x4c, 0x45, 0x10, 0x05, 0x12, 0x11, 0x0a, 0x0d, 0x53, 0x71, 0x6c, 0x4f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x6f, 0x72, 0x49, 0x6e, 0x10, 0x06, 0x12, 0x14, 0x0a, 0x10, 0x53, 0x71, 0x6c, 0x4f,
	0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x4e, 0x6f, 0x74, 0x49, 0x6e, 0x10, 0x07, 0x12, 0x18,
	0x0a, 0x14, 0x53, 0x71, 0x6c, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x46, 0x69, 0x6e,
	0x64, 0x49, 0x6e, 0x53, 0x65, 0x74, 0x10, 0x08, 0x12, 0x13, 0x0a, 0x0f, 0x53, 0x71, 0x6c, 0x4f,
	0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x4c, 0x69, 0x6b, 0x65, 0x10, 0x09, 0x12, 0x17, 0x0a,
	0x13, 0x53, 0x71, 0x6c, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x4c, 0x69, 0x6b, 0x65,
	0x4c, 0x65, 0x66, 0x74, 0x10, 0x0a, 0x12, 0x18, 0x0a, 0x14, 0x53, 0x71, 0x6c, 0x4f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x6f, 0x72, 0x4c, 0x69, 0x6b, 0x65, 0x52, 0x69, 0x67, 0x68, 0x74, 0x10, 0x0b,
	0x12, 0x16, 0x0a, 0x12, 0x53, 0x71, 0x6c, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x4e,
	0x6f, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x10, 0x0c, 0x12, 0x1a, 0x0a, 0x16, 0x53, 0x71, 0x6c, 0x4f,
	0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x4e, 0x6f, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x4c, 0x65,
	0x66, 0x74, 0x10, 0x0d, 0x12, 0x1b, 0x0a, 0x17, 0x53, 0x71, 0x6c, 0x4f, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x6f, 0x72, 0x4e, 0x6f, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x52, 0x69, 0x67, 0x68, 0x74, 0x10,
	0x0e, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x63, 0x70, 0x3b, 0x63, 0x70, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_message_admin_proto_rawDescOnce sync.Once
	file_message_admin_proto_rawDescData = file_message_admin_proto_rawDesc
)

func file_message_admin_proto_rawDescGZIP() []byte {
	file_message_admin_proto_rawDescOnce.Do(func() {
		file_message_admin_proto_rawDescData = protoimpl.X.CompressGZIP(file_message_admin_proto_rawDescData)
	})
	return file_message_admin_proto_rawDescData
}

var file_message_admin_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_message_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_message_admin_proto_goTypes = []interface{}{
	(AdminCommon_Sort)(0),                       // 0: cp.AdminCommon.Sort
	(AdminCommon_SqlOperator)(0),                // 1: cp.AdminCommon.SqlOperator
	(*AdminCommon)(nil),                         // 2: cp.AdminCommon
	(*AdminCommon_ListReq)(nil),                 // 3: cp.AdminCommon.ListReq
	(*AdminCommon_CascadeFilterRes)(nil),        // 4: cp.AdminCommon.CascadeFilterRes
	(*AdminCommon_CascadeFilterRes_Option)(nil), // 5: cp.AdminCommon.CascadeFilterRes.Option
}
var file_message_admin_proto_depIdxs = []int32{
	0, // 0: cp.AdminCommon.ListReq.order_sort:type_name -> cp.AdminCommon.Sort
	5, // 1: cp.AdminCommon.CascadeFilterRes.filters:type_name -> cp.AdminCommon.CascadeFilterRes.Option
	5, // 2: cp.AdminCommon.CascadeFilterRes.Option.children:type_name -> cp.AdminCommon.CascadeFilterRes.Option
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_message_admin_proto_init() }
func file_message_admin_proto_init() {
	if File_message_admin_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_message_admin_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdminCommon); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_admin_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdminCommon_ListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_admin_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdminCommon_CascadeFilterRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_admin_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdminCommon_CascadeFilterRes_Option); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_message_admin_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_admin_proto_goTypes,
		DependencyIndexes: file_message_admin_proto_depIdxs,
		EnumInfos:         file_message_admin_proto_enumTypes,
		MessageInfos:      file_message_admin_proto_msgTypes,
	}.Build()
	File_message_admin_proto = out.File
	file_message_admin_proto_rawDesc = nil
	file_message_admin_proto_goTypes = nil
	file_message_admin_proto_depIdxs = nil
}
