// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: message/common.proto

package cp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 页面类型
type PageType int32

const (
	// 未知
	PageType_UnKnown PageType = 0
	// 登录
	PageType_app_login PageType = 1
	// 小说详情
	PageType_app_book_info PageType = 2
	// 有声
	PageType_app_drama_info PageType = 3
	// 书单
	PageType_app_book_list_info PageType = 4
	// 章节
	PageType_app_read_page_transfer PageType = 5
	// 动态详情
	PageType_app_fishpond_detail PageType = 6
)

// Enum value maps for PageType.
var (
	PageType_name = map[int32]string{
		0: "UnKnown",
		1: "app_login",
		2: "app_book_info",
		3: "app_drama_info",
		4: "app_book_list_info",
		5: "app_read_page_transfer",
		6: "app_fishpond_detail",
	}
	PageType_value = map[string]int32{
		"UnKnown":                0,
		"app_login":              1,
		"app_book_info":          2,
		"app_drama_info":         3,
		"app_book_list_info":     4,
		"app_read_page_transfer": 5,
		"app_fishpond_detail":    6,
	}
)

func (x PageType) Enum() *PageType {
	p := new(PageType)
	*p = x
	return p
}

func (x PageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PageType) Descriptor() protoreflect.EnumDescriptor {
	return file_message_common_proto_enumTypes[0].Descriptor()
}

func (PageType) Type() protoreflect.EnumType {
	return &file_message_common_proto_enumTypes[0]
}

func (x PageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PageType.Descriptor instead.
func (PageType) EnumDescriptor() ([]byte, []int) {
	return file_message_common_proto_rawDescGZIP(), []int{0}
}

// SortAsc -- 升序, SortDesc -- 降序
type Sort int32

const (
	Sort_SortAsc  Sort = 0
	Sort_SortDesc Sort = 1
)

// Enum value maps for Sort.
var (
	Sort_name = map[int32]string{
		0: "SortAsc",
		1: "SortDesc",
	}
	Sort_value = map[string]int32{
		"SortAsc":  0,
		"SortDesc": 1,
	}
)

func (x Sort) Enum() *Sort {
	p := new(Sort)
	*p = x
	return p
}

func (x Sort) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Sort) Descriptor() protoreflect.EnumDescriptor {
	return file_message_common_proto_enumTypes[1].Descriptor()
}

func (Sort) Type() protoreflect.EnumType {
	return &file_message_common_proto_enumTypes[1]
}

func (x Sort) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Sort.Descriptor instead.
func (Sort) EnumDescriptor() ([]byte, []int) {
	return file_message_common_proto_rawDescGZIP(), []int{1}
}

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_common_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_message_common_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_message_common_proto_rawDescGZIP(), []int{0}
}

type Url struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// 为了匹配前端h5路由，传PageType时需要传额外的匹配h5路由的参数
	// 例如 PageType为NovelInfo时，前端的路径为：https://www.gongzicp.com/novel-484311.html，
	// 此时query中的参数需要有小说 id:484311
	// 注：一般是分享链接时需要这样传
	Query    map[string]string `protobuf:"bytes,2,rep,name=query,proto3" json:"query,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	PageType PageType          `protobuf:"varint,3,opt,name=page_type,json=pageType,proto3,enum=cp.PageType" json:"page_type,omitempty"`
}

func (x *Url) Reset() {
	*x = Url{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_common_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Url) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Url) ProtoMessage() {}

func (x *Url) ProtoReflect() protoreflect.Message {
	mi := &file_message_common_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Url.ProtoReflect.Descriptor instead.
func (*Url) Descriptor() ([]byte, []int) {
	return file_message_common_proto_rawDescGZIP(), []int{1}
}

func (x *Url) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Url) GetQuery() map[string]string {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *Url) GetPageType() PageType {
	if x != nil {
		return x.PageType
	}
	return PageType_UnKnown
}

type BooleanValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Flag bool `protobuf:"varint,1,opt,name=flag,proto3" json:"flag,omitempty"`
}

func (x *BooleanValue) Reset() {
	*x = BooleanValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_common_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BooleanValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BooleanValue) ProtoMessage() {}

func (x *BooleanValue) ProtoReflect() protoreflect.Message {
	mi := &file_message_common_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BooleanValue.ProtoReflect.Descriptor instead.
func (*BooleanValue) Descriptor() ([]byte, []int) {
	return file_message_common_proto_rawDescGZIP(), []int{2}
}

func (x *BooleanValue) GetFlag() bool {
	if x != nil {
		return x.Flag
	}
	return false
}

var File_message_common_proto protoreflect.FileDescriptor

var file_message_common_proto_rawDesc = []byte{
	0x0a, 0x14, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x63, 0x70, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x22, 0xa8, 0x01, 0x0a, 0x03, 0x55, 0x72, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x70,
	0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12,
	0x28, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12,
	0x2e, 0x63, 0x70, 0x2e, 0x55, 0x72, 0x6c, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x12, 0x29, 0x0a, 0x09, 0x70, 0x61, 0x67,
	0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x63,
	0x70, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65,
	0x54, 0x79, 0x70, 0x65, 0x1a, 0x38, 0x0a, 0x0a, 0x51, 0x75, 0x65, 0x72, 0x79, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x22,
	0x0a, 0x0c, 0x42, 0x6f, 0x6f, 0x6c, 0x65, 0x61, 0x6e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x66, 0x6c,
	0x61, 0x67, 0x2a, 0x9a, 0x01, 0x0a, 0x08, 0x50, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x0b, 0x0a, 0x07, 0x55, 0x6e, 0x4b, 0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09,
	0x61, 0x70, 0x70, 0x5f, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x10, 0x01, 0x12, 0x11, 0x0a, 0x0d, 0x61,
	0x70, 0x70, 0x5f, 0x62, 0x6f, 0x6f, 0x6b, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x10, 0x02, 0x12, 0x12,
	0x0a, 0x0e, 0x61, 0x70, 0x70, 0x5f, 0x64, 0x72, 0x61, 0x6d, 0x61, 0x5f, 0x69, 0x6e, 0x66, 0x6f,
	0x10, 0x03, 0x12, 0x16, 0x0a, 0x12, 0x61, 0x70, 0x70, 0x5f, 0x62, 0x6f, 0x6f, 0x6b, 0x5f, 0x6c,
	0x69, 0x73, 0x74, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x10, 0x04, 0x12, 0x1a, 0x0a, 0x16, 0x61, 0x70,
	0x70, 0x5f, 0x72, 0x65, 0x61, 0x64, 0x5f, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x74, 0x72, 0x61, 0x6e,
	0x73, 0x66, 0x65, 0x72, 0x10, 0x05, 0x12, 0x17, 0x0a, 0x13, 0x61, 0x70, 0x70, 0x5f, 0x66, 0x69,
	0x73, 0x68, 0x70, 0x6f, 0x6e, 0x64, 0x5f, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x10, 0x06, 0x2a,
	0x21, 0x0a, 0x04, 0x53, 0x6f, 0x72, 0x74, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x6f, 0x72, 0x74, 0x41,
	0x73, 0x63, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x53, 0x6f, 0x72, 0x74, 0x44, 0x65, 0x73, 0x63,
	0x10, 0x01, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x63, 0x70, 0x3b, 0x63, 0x70, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_message_common_proto_rawDescOnce sync.Once
	file_message_common_proto_rawDescData = file_message_common_proto_rawDesc
)

func file_message_common_proto_rawDescGZIP() []byte {
	file_message_common_proto_rawDescOnce.Do(func() {
		file_message_common_proto_rawDescData = protoimpl.X.CompressGZIP(file_message_common_proto_rawDescData)
	})
	return file_message_common_proto_rawDescData
}

var file_message_common_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_message_common_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_message_common_proto_goTypes = []interface{}{
	(PageType)(0),        // 0: cp.PageType
	(Sort)(0),            // 1: cp.Sort
	(*Empty)(nil),        // 2: cp.Empty
	(*Url)(nil),          // 3: cp.Url
	(*BooleanValue)(nil), // 4: cp.BooleanValue
	nil,                  // 5: cp.Url.QueryEntry
}
var file_message_common_proto_depIdxs = []int32{
	5, // 0: cp.Url.query:type_name -> cp.Url.QueryEntry
	0, // 1: cp.Url.page_type:type_name -> cp.PageType
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_message_common_proto_init() }
func file_message_common_proto_init() {
	if File_message_common_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_message_common_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_common_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Url); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_common_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BooleanValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_message_common_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_common_proto_goTypes,
		DependencyIndexes: file_message_common_proto_depIdxs,
		EnumInfos:         file_message_common_proto_enumTypes,
		MessageInfos:      file_message_common_proto_msgTypes,
	}.Build()
	File_message_common_proto = out.File
	file_message_common_proto_rawDesc = nil
	file_message_common_proto_goTypes = nil
	file_message_common_proto_depIdxs = nil
}
