// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: message/user.proto

package cp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 用户关系
type UserCommon_Relation int32

const (
	// 没有关系
	UserCommon_RelationNone UserCommon_Relation = 0
	// 关注
	UserCommon_RelationFollow UserCommon_Relation = 1
	// 拉黑
	UserCommon_RelationBlock UserCommon_Relation = 2
	// 自己
	UserCommon_RelationOwn UserCommon_Relation = 3
)

// Enum value maps for UserCommon_Relation.
var (
	UserCommon_Relation_name = map[int32]string{
		0: "RelationNone",
		1: "RelationFollow",
		2: "RelationBlock",
		3: "RelationOwn",
	}
	UserCommon_Relation_value = map[string]int32{
		"RelationNone":   0,
		"RelationFollow": 1,
		"RelationBlock":  2,
		"RelationOwn":    3,
	}
)

func (x UserCommon_Relation) Enum() *UserCommon_Relation {
	p := new(UserCommon_Relation)
	*p = x
	return p
}

func (x UserCommon_Relation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserCommon_Relation) Descriptor() protoreflect.EnumDescriptor {
	return file_message_user_proto_enumTypes[0].Descriptor()
}

func (UserCommon_Relation) Type() protoreflect.EnumType {
	return &file_message_user_proto_enumTypes[0]
}

func (x UserCommon_Relation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserCommon_Relation.Descriptor instead.
func (UserCommon_Relation) EnumDescriptor() ([]byte, []int) {
	return file_message_user_proto_rawDescGZIP(), []int{0, 0}
}

// 用户身份认证
type UserCommon_Identity int32

const (
	// 未知
	UserCommon_IdentityUnknown UserCommon_Identity = 0
	// 普通用户
	UserCommon_IdentityNormal UserCommon_Identity = 1
	// 黄V，签约作者，头像带黄色V标，个人空间显示长佩签约作者
	UserCommon_IdentityYellowV UserCommon_Identity = 2
	// 蓝V，官方，头像带蓝色V标，个人空间显示长佩官方账号
	UserCommon_IdentityBlueV UserCommon_Identity = 3
)

// Enum value maps for UserCommon_Identity.
var (
	UserCommon_Identity_name = map[int32]string{
		0: "IdentityUnknown",
		1: "IdentityNormal",
		2: "IdentityYellowV",
		3: "IdentityBlueV",
	}
	UserCommon_Identity_value = map[string]int32{
		"IdentityUnknown": 0,
		"IdentityNormal":  1,
		"IdentityYellowV": 2,
		"IdentityBlueV":   3,
	}
)

func (x UserCommon_Identity) Enum() *UserCommon_Identity {
	p := new(UserCommon_Identity)
	*p = x
	return p
}

func (x UserCommon_Identity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserCommon_Identity) Descriptor() protoreflect.EnumDescriptor {
	return file_message_user_proto_enumTypes[1].Descriptor()
}

func (UserCommon_Identity) Type() protoreflect.EnumType {
	return &file_message_user_proto_enumTypes[1]
}

func (x UserCommon_Identity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserCommon_Identity.Descriptor instead.
func (UserCommon_Identity) EnumDescriptor() ([]byte, []int) {
	return file_message_user_proto_rawDescGZIP(), []int{0, 1}
}

// 禁言范围
type UserCommon_ForbidTalkRange int32

const (
	// 未知
	UserCommon_ForbidTalkRangeUnknown UserCommon_ForbidTalkRange = 0
	// 评论
	UserCommon_ForbidTalkRangeComment UserCommon_ForbidTalkRange = 1
	// 作品、章节
	UserCommon_ForbidTalkRangeNovel UserCommon_ForbidTalkRange = 2
	// 书单
	UserCommon_ForbidTalkRangeBook UserCommon_ForbidTalkRange = 3
	// 动态
	UserCommon_ForbidTalkRangeMoment UserCommon_ForbidTalkRange = 4
)

// Enum value maps for UserCommon_ForbidTalkRange.
var (
	UserCommon_ForbidTalkRange_name = map[int32]string{
		0: "ForbidTalkRangeUnknown",
		1: "ForbidTalkRangeComment",
		2: "ForbidTalkRangeNovel",
		3: "ForbidTalkRangeBook",
		4: "ForbidTalkRangeMoment",
	}
	UserCommon_ForbidTalkRange_value = map[string]int32{
		"ForbidTalkRangeUnknown": 0,
		"ForbidTalkRangeComment": 1,
		"ForbidTalkRangeNovel":   2,
		"ForbidTalkRangeBook":    3,
		"ForbidTalkRangeMoment":  4,
	}
)

func (x UserCommon_ForbidTalkRange) Enum() *UserCommon_ForbidTalkRange {
	p := new(UserCommon_ForbidTalkRange)
	*p = x
	return p
}

func (x UserCommon_ForbidTalkRange) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserCommon_ForbidTalkRange) Descriptor() protoreflect.EnumDescriptor {
	return file_message_user_proto_enumTypes[2].Descriptor()
}

func (UserCommon_ForbidTalkRange) Type() protoreflect.EnumType {
	return &file_message_user_proto_enumTypes[2]
}

func (x UserCommon_ForbidTalkRange) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserCommon_ForbidTalkRange.Descriptor instead.
func (UserCommon_ForbidTalkRange) EnumDescriptor() ([]byte, []int) {
	return file_message_user_proto_rawDescGZIP(), []int{0, 2}
}

type UserCommon struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UserCommon) Reset() {
	*x = UserCommon{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_user_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserCommon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCommon) ProtoMessage() {}

func (x *UserCommon) ProtoReflect() protoreflect.Message {
	mi := &file_message_user_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCommon.ProtoReflect.Descriptor instead.
func (*UserCommon) Descriptor() ([]byte, []int) {
	return file_message_user_proto_rawDescGZIP(), []int{0}
}

// 用户详情结构，用于空间和个人中心
type UserCommon_InfoUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid uint32 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	// 昵称
	Nickname string `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	// 头像
	Avatar string `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	// 勋章
	Medal string `protobuf:"bytes,4,opt,name=medal,proto3" json:"medal,omitempty"`
	// 挂件
	Pendant string `protobuf:"bytes,5,opt,name=pendant,proto3" json:"pendant,omitempty"`
	// 等级
	Level uint32 `protobuf:"varint,6,opt,name=level,proto3" json:"level,omitempty"`
	// 身份认证
	Identity UserCommon_Identity `protobuf:"varint,7,opt,name=identity,proto3,enum=cp.UserCommon_Identity" json:"identity,omitempty"`
	// 关注数
	Follows uint32 `protobuf:"varint,8,opt,name=follows,proto3" json:"follows,omitempty"`
	// 粉丝数
	Fans uint32 `protobuf:"varint,9,opt,name=fans,proto3" json:"fans,omitempty"`
	// 个性签名
	Sign string `protobuf:"bytes,10,opt,name=sign,proto3" json:"sign,omitempty"`
	// 创作字数
	WordNumber uint32 `protobuf:"varint,11,opt,name=word_number,json=wordNumber,proto3" json:"word_number,omitempty"`
	// 用户关系，当前登录用户与此用户的关系
	Relation UserCommon_Relation `protobuf:"varint,12,opt,name=relation,proto3,enum=cp.UserCommon_Relation" json:"relation,omitempty"`
	// 用户空间背景
	Background string `protobuf:"bytes,13,opt,name=background,proto3" json:"background,omitempty"`
	// 作者ID，可作为是否是作者的判断依据
	Aid uint32 `protobuf:"varint,14,opt,name=aid,proto3" json:"aid,omitempty"`
}

func (x *UserCommon_InfoUser) Reset() {
	*x = UserCommon_InfoUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_user_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserCommon_InfoUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCommon_InfoUser) ProtoMessage() {}

func (x *UserCommon_InfoUser) ProtoReflect() protoreflect.Message {
	mi := &file_message_user_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCommon_InfoUser.ProtoReflect.Descriptor instead.
func (*UserCommon_InfoUser) Descriptor() ([]byte, []int) {
	return file_message_user_proto_rawDescGZIP(), []int{0, 0}
}

func (x *UserCommon_InfoUser) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *UserCommon_InfoUser) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UserCommon_InfoUser) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UserCommon_InfoUser) GetMedal() string {
	if x != nil {
		return x.Medal
	}
	return ""
}

func (x *UserCommon_InfoUser) GetPendant() string {
	if x != nil {
		return x.Pendant
	}
	return ""
}

func (x *UserCommon_InfoUser) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *UserCommon_InfoUser) GetIdentity() UserCommon_Identity {
	if x != nil {
		return x.Identity
	}
	return UserCommon_IdentityUnknown
}

func (x *UserCommon_InfoUser) GetFollows() uint32 {
	if x != nil {
		return x.Follows
	}
	return 0
}

func (x *UserCommon_InfoUser) GetFans() uint32 {
	if x != nil {
		return x.Fans
	}
	return 0
}

func (x *UserCommon_InfoUser) GetSign() string {
	if x != nil {
		return x.Sign
	}
	return ""
}

func (x *UserCommon_InfoUser) GetWordNumber() uint32 {
	if x != nil {
		return x.WordNumber
	}
	return 0
}

func (x *UserCommon_InfoUser) GetRelation() UserCommon_Relation {
	if x != nil {
		return x.Relation
	}
	return UserCommon_RelationNone
}

func (x *UserCommon_InfoUser) GetBackground() string {
	if x != nil {
		return x.Background
	}
	return ""
}

func (x *UserCommon_InfoUser) GetAid() uint32 {
	if x != nil {
		return x.Aid
	}
	return 0
}

// 用户基础结构，用于列表
type UserCommon_BasicUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid uint32 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	// 昵称
	Nickname string `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	// 头像
	Avatar string `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	// 勋章
	Medal string `protobuf:"bytes,4,opt,name=medal,proto3" json:"medal,omitempty"`
	// 挂件
	Pendant string `protobuf:"bytes,5,opt,name=pendant,proto3" json:"pendant,omitempty"`
	// 等级
	Level uint32 `protobuf:"varint,6,opt,name=level,proto3" json:"level,omitempty"`
	// 身份认证
	Identity UserCommon_Identity `protobuf:"varint,7,opt,name=identity,proto3,enum=cp.UserCommon_Identity" json:"identity,omitempty"`
	// 个性签名
	Sign string `protobuf:"bytes,8,opt,name=sign,proto3" json:"sign,omitempty"`
}

func (x *UserCommon_BasicUser) Reset() {
	*x = UserCommon_BasicUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_user_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserCommon_BasicUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCommon_BasicUser) ProtoMessage() {}

func (x *UserCommon_BasicUser) ProtoReflect() protoreflect.Message {
	mi := &file_message_user_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCommon_BasicUser.ProtoReflect.Descriptor instead.
func (*UserCommon_BasicUser) Descriptor() ([]byte, []int) {
	return file_message_user_proto_rawDescGZIP(), []int{0, 1}
}

func (x *UserCommon_BasicUser) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *UserCommon_BasicUser) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UserCommon_BasicUser) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UserCommon_BasicUser) GetMedal() string {
	if x != nil {
		return x.Medal
	}
	return ""
}

func (x *UserCommon_BasicUser) GetPendant() string {
	if x != nil {
		return x.Pendant
	}
	return ""
}

func (x *UserCommon_BasicUser) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *UserCommon_BasicUser) GetIdentity() UserCommon_Identity {
	if x != nil {
		return x.Identity
	}
	return UserCommon_IdentityUnknown
}

func (x *UserCommon_BasicUser) GetSign() string {
	if x != nil {
		return x.Sign
	}
	return ""
}

// 用户最简单的结构，用于没有头像的列表
type UserCommon_SimpleUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid uint32 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	// 昵称
	Nickname string `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
}

func (x *UserCommon_SimpleUser) Reset() {
	*x = UserCommon_SimpleUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_user_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserCommon_SimpleUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCommon_SimpleUser) ProtoMessage() {}

func (x *UserCommon_SimpleUser) ProtoReflect() protoreflect.Message {
	mi := &file_message_user_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCommon_SimpleUser.ProtoReflect.Descriptor instead.
func (*UserCommon_SimpleUser) Descriptor() ([]byte, []int) {
	return file_message_user_proto_rawDescGZIP(), []int{0, 2}
}

func (x *UserCommon_SimpleUser) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *UserCommon_SimpleUser) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

type UserCommon_BindingInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 手机号，带区号并隐藏中间几位。例如 +86 123****8888
	Tel string `protobuf:"bytes,1,opt,name=tel,proto3" json:"tel,omitempty"`
	// 邮箱
	Email string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	// 微博
	Weibo string `protobuf:"bytes,3,opt,name=weibo,proto3" json:"weibo,omitempty"`
	// qq
	Qq string `protobuf:"bytes,4,opt,name=qq,proto3" json:"qq,omitempty"`
	// 微信
	WeChat string `protobuf:"bytes,5,opt,name=we_chat,json=weChat,proto3" json:"we_chat,omitempty"`
}

func (x *UserCommon_BindingInfo) Reset() {
	*x = UserCommon_BindingInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_message_user_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserCommon_BindingInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCommon_BindingInfo) ProtoMessage() {}

func (x *UserCommon_BindingInfo) ProtoReflect() protoreflect.Message {
	mi := &file_message_user_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCommon_BindingInfo.ProtoReflect.Descriptor instead.
func (*UserCommon_BindingInfo) Descriptor() ([]byte, []int) {
	return file_message_user_proto_rawDescGZIP(), []int{0, 3}
}

func (x *UserCommon_BindingInfo) GetTel() string {
	if x != nil {
		return x.Tel
	}
	return ""
}

func (x *UserCommon_BindingInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserCommon_BindingInfo) GetWeibo() string {
	if x != nil {
		return x.Weibo
	}
	return ""
}

func (x *UserCommon_BindingInfo) GetQq() string {
	if x != nil {
		return x.Qq
	}
	return ""
}

func (x *UserCommon_BindingInfo) GetWeChat() string {
	if x != nil {
		return x.WeChat
	}
	return ""
}

var File_message_user_proto protoreflect.FileDescriptor

var file_message_user_proto_rawDesc = []byte{
	0x0a, 0x12, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x63, 0x70, 0x22, 0x86, 0x09, 0x0a, 0x0a, 0x55, 0x73, 0x65,
	0x72, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x1a, 0x95, 0x03, 0x0a, 0x08, 0x49, 0x6e, 0x66, 0x6f,
	0x55, 0x73, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x65,
	0x64, 0x61, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x65, 0x64, 0x61, 0x6c,
	0x12, 0x18, 0x0a, 0x07, 0x70, 0x65, 0x6e, 0x64, 0x61, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x70, 0x65, 0x6e, 0x64, 0x61, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65,
	0x76, 0x65, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c,
	0x12, 0x33, 0x0a, 0x08, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x17, 0x2e, 0x63, 0x70, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x43, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2e, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x08, 0x69, 0x64, 0x65,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x73,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x66, 0x6f, 0x6c, 0x6c, 0x6f, 0x77, 0x73, 0x12,
	0x12, 0x0a, 0x04, 0x66, 0x61, 0x6e, 0x73, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x66,
	0x61, 0x6e, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x67, 0x6e, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x73, 0x69, 0x67, 0x6e, 0x12, 0x1f, 0x0a, 0x0b, 0x77, 0x6f, 0x72, 0x64, 0x5f,
	0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x77, 0x6f,
	0x72, 0x64, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x33, 0x0a, 0x08, 0x72, 0x65, 0x6c, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x63, 0x70, 0x2e,
	0x55, 0x73, 0x65, 0x72, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x6c, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x08, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x0a,
	0x0a, 0x62, 0x61, 0x63, 0x6b, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x0d, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x62, 0x61, 0x63, 0x6b, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x12, 0x10, 0x0a,
	0x03, 0x61, 0x69, 0x64, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x61, 0x69, 0x64, 0x1a,
	0xe0, 0x01, 0x0a, 0x09, 0x42, 0x61, 0x73, 0x69, 0x63, 0x55, 0x73, 0x65, 0x72, 0x12, 0x10, 0x0a,
	0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12,
	0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61,
	0x76, 0x61, 0x74, 0x61, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x76, 0x61,
	0x74, 0x61, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x65, 0x64, 0x61, 0x6c, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x6d, 0x65, 0x64, 0x61, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x65, 0x6e,
	0x64, 0x61, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x65, 0x6e, 0x64,
	0x61, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x33, 0x0a, 0x08, 0x69, 0x64, 0x65,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x63, 0x70,
	0x2e, 0x55, 0x73, 0x65, 0x72, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x49, 0x64, 0x65, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x52, 0x08, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x12,
	0x0a, 0x04, 0x73, 0x69, 0x67, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x69,
	0x67, 0x6e, 0x1a, 0x3a, 0x0a, 0x0a, 0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x55, 0x73, 0x65, 0x72,
	0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x75,
	0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x1a, 0x74,
	0x0a, 0x0b, 0x42, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x10, 0x0a,
	0x03, 0x74, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x74, 0x65, 0x6c, 0x12,
	0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x65, 0x69, 0x62, 0x6f, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x77, 0x65, 0x69, 0x62, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x71,
	0x71, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x71, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x77,
	0x65, 0x5f, 0x63, 0x68, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x77, 0x65,
	0x43, 0x68, 0x61, 0x74, 0x22, 0x54, 0x0a, 0x08, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x10, 0x0a, 0x0c, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x6f, 0x6e, 0x65,
	0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x46, 0x6f,
	0x6c, 0x6c, 0x6f, 0x77, 0x10, 0x01, 0x12, 0x11, 0x0a, 0x0d, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x10, 0x02, 0x12, 0x0f, 0x0a, 0x0b, 0x52, 0x65, 0x6c,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4f, 0x77, 0x6e, 0x10, 0x03, 0x22, 0x5b, 0x0a, 0x08, 0x49, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x13, 0x0a, 0x0f, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e, 0x49,
	0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x4e, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x10, 0x01, 0x12,
	0x13, 0x0a, 0x0f, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x59, 0x65, 0x6c, 0x6c, 0x6f,
	0x77, 0x56, 0x10, 0x02, 0x12, 0x11, 0x0a, 0x0d, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x42, 0x6c, 0x75, 0x65, 0x56, 0x10, 0x03, 0x22, 0x97, 0x01, 0x0a, 0x0f, 0x46, 0x6f, 0x72, 0x62,
	0x69, 0x64, 0x54, 0x61, 0x6c, 0x6b, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x16, 0x46,
	0x6f, 0x72, 0x62, 0x69, 0x64, 0x54, 0x61, 0x6c, 0x6b, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x55, 0x6e,
	0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x00, 0x12, 0x1a, 0x0a, 0x16, 0x46, 0x6f, 0x72, 0x62, 0x69,
	0x64, 0x54, 0x61, 0x6c, 0x6b, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e,
	0x74, 0x10, 0x01, 0x12, 0x18, 0x0a, 0x14, 0x46, 0x6f, 0x72, 0x62, 0x69, 0x64, 0x54, 0x61, 0x6c,
	0x6b, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x4e, 0x6f, 0x76, 0x65, 0x6c, 0x10, 0x02, 0x12, 0x17, 0x0a,
	0x13, 0x46, 0x6f, 0x72, 0x62, 0x69, 0x64, 0x54, 0x61, 0x6c, 0x6b, 0x52, 0x61, 0x6e, 0x67, 0x65,
	0x42, 0x6f, 0x6f, 0x6b, 0x10, 0x03, 0x12, 0x19, 0x0a, 0x15, 0x46, 0x6f, 0x72, 0x62, 0x69, 0x64,
	0x54, 0x61, 0x6c, 0x6b, 0x52, 0x61, 0x6e, 0x67, 0x65, 0x4d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x10,
	0x04, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x63, 0x70, 0x3b, 0x63, 0x70, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_message_user_proto_rawDescOnce sync.Once
	file_message_user_proto_rawDescData = file_message_user_proto_rawDesc
)

func file_message_user_proto_rawDescGZIP() []byte {
	file_message_user_proto_rawDescOnce.Do(func() {
		file_message_user_proto_rawDescData = protoimpl.X.CompressGZIP(file_message_user_proto_rawDescData)
	})
	return file_message_user_proto_rawDescData
}

var file_message_user_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_message_user_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_message_user_proto_goTypes = []interface{}{
	(UserCommon_Relation)(0),        // 0: cp.UserCommon.Relation
	(UserCommon_Identity)(0),        // 1: cp.UserCommon.Identity
	(UserCommon_ForbidTalkRange)(0), // 2: cp.UserCommon.ForbidTalkRange
	(*UserCommon)(nil),              // 3: cp.UserCommon
	(*UserCommon_InfoUser)(nil),     // 4: cp.UserCommon.InfoUser
	(*UserCommon_BasicUser)(nil),    // 5: cp.UserCommon.BasicUser
	(*UserCommon_SimpleUser)(nil),   // 6: cp.UserCommon.SimpleUser
	(*UserCommon_BindingInfo)(nil),  // 7: cp.UserCommon.BindingInfo
}
var file_message_user_proto_depIdxs = []int32{
	1, // 0: cp.UserCommon.InfoUser.identity:type_name -> cp.UserCommon.Identity
	0, // 1: cp.UserCommon.InfoUser.relation:type_name -> cp.UserCommon.Relation
	1, // 2: cp.UserCommon.BasicUser.identity:type_name -> cp.UserCommon.Identity
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_message_user_proto_init() }
func file_message_user_proto_init() {
	if File_message_user_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_message_user_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserCommon); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_user_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserCommon_InfoUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_user_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserCommon_BasicUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_user_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserCommon_SimpleUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_message_user_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserCommon_BindingInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_message_user_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_user_proto_goTypes,
		DependencyIndexes: file_message_user_proto_depIdxs,
		EnumInfos:         file_message_user_proto_enumTypes,
		MessageInfos:      file_message_user_proto_msgTypes,
	}.Build()
	File_message_user_proto = out.File
	file_message_user_proto_rawDesc = nil
	file_message_user_proto_goTypes = nil
	file_message_user_proto_depIdxs = nil
}
